import numpy
import pyaudio
import sys
import librosa

DEVICE_NAME = "RODE NT-USB"
FORMAT = pyaudio.paInt16
CHANNELS = 1
RATE = 44100
CHUNK_SECONDS = 7.5
NUMPY_DATA_TYPE = numpy.int16
MIN_NOTE_LENGTH = 1
MIN_FREQ = librosa.note_to_hz("E2")
MAX_FREQ = librosa.note_to_hz("A4")
NOTES_TO_PROCESS = 15
TEMPOS_TO_PROCESS = 5
MIN_OUTPUT_LENGTH = 5
MAX_OUTPUT_LENGTH = 25
SEQUENCE_GENERATION_PROBABILITY = 0.4
MIDI_INSTRUMENT = 5
CHUNKS_TO_ANALYZE_TEMPO = 10
MAX_REPEAT_NOTES = 1
